### ISSUE TITLE
Preset select popup menu opens immediately on program start

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#8] opened 2016-03-18 11:39 UTC
The popup menu open directly under the mouse pointer, where ever that may be at the time.

![jalv-select-popup](https://cloud.githubusercontent.com/assets/5719151/13876715/72a85672-ed06-11e5-859d-878b7a2cbc55.png)

**Comment by brummer10** [comment] 2016-03-18 12:44
Mmm, can't reproduce it here. However, I've pushed a possible Fix for this, let me know please if it helps.

**Comment by SpotlightKid** [comment] 2016-03-18 13:03
Sorry, no. Still same behaviour.

**Comment by brummer10** [comment] 2016-03-18 13:37
When you click on the popup menu, which plugin get loaded, is it the first or the last in the list?

**Comment by SpotlightKid** [comment] 2016-03-18 13:43
The first. Calf Analyzer in my case.

**Comment by brummer10** [comment] 2016-03-18 16:57
So I've made one more try, to bad, I can't reproduce it here, so it may again not work. 
My guess is, that the focus is set to the TreeView, and activate the first entry. I try to avoid that now, let me know, if it work.

regards
hermann

**Comment by SpotlightKid** [comment] 2016-03-18 17:23
Yes, seems fixed here.

**Comment by brummer10** [comment] 2016-03-18 18:37
Okay, that's great.
So I've pushed a new tag to V0.4
with the fix.

regards
hermann

**Closed as completed by brummer10** 2016-03-18 18:37 UTC

**Comment by SpotlightKid** [comment] 2016-03-23 11:49
The error returned in version 0.5. Same behaviour, preset selection popup opens on application start. Selecting it, opens first plugin in list.

**Comment by brummer10** [comment] 2016-03-23 12:16
Oh shi\* hopefully I've now find a way to avoid this error for ever.
regards
hermann

**Comment by SpotlightKid** [comment] 2016-03-25 11:10
Seems fixed in version 0.6.
